# Generated by Django 5.2.6 on 2025-10-10 08:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SessionApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="end_time",
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="session",
            name="room",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9\\s]+$",
                        "le nom de la salle ne doit contenir que des lettres et des chiffres pas de caractere speciaux",
                    )
                ],
            ),
        ),
    ]
