# Generated by Django 5.2.6 on 2025-09-26 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                ("conference_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("IA", "Computer science and Artificial Intelligence"),
                            ("SE", "Science and Engineering"),
                            ("SC", " Social Sciences & Education"),
                            ("IT", "Interdiscplinary Themes"),
                        ],
                        max_length=255,
                    ),
                ),
                ("location", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "submission_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.TextField()),
                ("abstarct", models.TextField()),
                ("keywords", models.FileField(upload_to="papers/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrganozingCommitee",
            fields=[
                (
                    "organizingcommitee_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "commitee_role",
                    models.CharField(
                        choices=[
                            ("chair", "chair"),
                            ("co_chair", "co_chair"),
                            ("member", "member"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_joined", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committees",
                        to="ConferenceApp.conference",
                    ),
                ),
            ],
        ),
    ]
