# Generated by Django 5.2.6 on 2025-10-03 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConferenceApp", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        500, "Vous avez dépassé la limite"
                    )
                ],
            ),
        ),
    ]
