# Generated by Django 5.2.6 on 2025-10-10 08:42

import ConferenceApp.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConferenceApp", "0003_conference_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="paper",
            field=models.FileField(
                default=django.utils.timezone.now,
                upload_to="papers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="submission_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="conference",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z\\s]+$",
                        "Le titre de la conférence ne doit contenir que des lettres et des espaces (pas de chiffres ou caractères spéciaux).",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="keywords",
            field=models.TextField(help_text="separer les mots_cles par des virgules "),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_id",
            field=models.CharField(
                default=ConferenceApp.models.generate_sub_id,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
